[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 300 -b 0.0.0.0:8080 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300