
'use client';

import { Link } from 'react-router-dom';
import Footer from '../components/Footer';
import Header from '../components/Header';
import BrainDiagram from '../components/BrainDiagram';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

export default function About() {
  return (
    <div
      className="relative flex flex-col min-h-screen text-white bg-center bg-cover"
      style={{ backgroundImage: "url('/bg-gradient.jpg')" }}
    >
      <div className="absolute inset-0 z-0 bg-black/30" />

      <Header />

      <main className="relative z-10 flex flex-col flex-grow w-full px-5 py-10 mx-auto" style={{ maxWidth: '1200px' }}>
        <div className="w-full mb-10">
          <Typography
            variant="h3"
            component="h1"
            sx={{
              fontWeight: 'bold',
              fontFamily: 'Neue Machina, sans-serif',
              mb: 4,
              letterSpacing: '0.15em',
              fontSize: {
                xs: '2.5rem',
                sm: '3rem',
                md: '3.5rem',
                lg: '4rem',
                xl: '5rem',
              },
              display: 'inline-flex',
              flexWrap: 'nowrap',
              alignItems: 'center',
              whiteSpace: 'nowrap',
            }}
          >
            About{' '}
            <Box
              component="span"
              sx={{
                ml: 1,
                background: 'linear-gradient(to right, #5de0e6, #004aad)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                display: 'inline',
                fontWeight: 'bold',
                fontFamily: 'Neue Machina Bold, sans-serif',
                letterSpacing: '0.15em',
              }}
            >
              MedScanAI
            </Box>
          </Typography>
        </div>

        <div className="w-full mb-16">
          <BrainDiagram />
        </div>

        <div className="w-full">
          <Typography
            variant="subtitle1"
            sx={{
              color: '#facc15',
              fontWeight: 'bold',
              fontFamily: 'Neue Machina Bold, sans-serif',
              letterSpacing: '0.05em',
            }}
          >
            ⚠️ Disclaimer
          </Typography>
          <Typography
            variant="body2"
            sx={{
              color: '#cbd5e1',
              fontFamily: 'Neue Machina, sans-serif',
              letterSpacing: '0.05em',
              fontSize: '1rem',
              lineHeight: 1.6,
              mt: 1,
            }}
          >
            MedScanAI is not a clinical diagnostic tool. The results generated by this platform are intended for informational and educational purposes only and should not be used as a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider before making any medical decisions based on scan interpretations.
          </Typography>
        </div>
      </main>

      <Footer />
    </div>
  );
}
