"""rename fields to snake_case

Revision ID: 12a3ccd012b7
Revises: c88efce9900f
Create Date: 2025-09-29 14:06:26.621406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12a3ccd012b7'
down_revision: Union[str, Sequence[str], None] = 'c88efce9900f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HospitalDomain', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('HospitalDomain', 'createdAt')
    op.add_column('Log', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('Log_userId_fkey', 'Log', type_='foreignkey')
    op.create_foreign_key(None, 'Log', 'User', ['user_id'], ['id'])
    op.drop_column('Log', 'userId')
    op.add_column('Prediction', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('Prediction_userId_fkey', 'Prediction', type_='foreignkey')
    op.create_foreign_key(None, 'Prediction', 'User', ['user_id'], ['id'])
    op.drop_column('Prediction', 'userId')
    op.add_column('Report', sa.Column('prediction_id', sa.UUID(), nullable=True))
    op.add_column('Report', sa.Column('doctor_id', sa.UUID(), nullable=True))
    op.drop_constraint('Report_doctorId_fkey', 'Report', type_='foreignkey')
    op.drop_constraint('Report_predictionId_fkey', 'Report', type_='foreignkey')
    op.create_foreign_key(None, 'Report', 'Prediction', ['prediction_id'], ['id'])
    op.create_foreign_key(None, 'Report', 'User', ['doctor_id'], ['id'])
    op.drop_column('Report', 'doctorId')
    op.drop_column('Report', 'predictionId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('predictionId', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Report', sa.Column('doctorId', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Report', type_='foreignkey')
    op.drop_constraint(None, 'Report', type_='foreignkey')
    op.create_foreign_key('Report_predictionId_fkey', 'Report', 'Prediction', ['predictionId'], ['id'])
    op.create_foreign_key('Report_doctorId_fkey', 'Report', 'User', ['doctorId'], ['id'])
    op.drop_column('Report', 'doctor_id')
    op.drop_column('Report', 'prediction_id')
    op.add_column('Prediction', sa.Column('userId', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Prediction', type_='foreignkey')
    op.create_foreign_key('Prediction_userId_fkey', 'Prediction', 'User', ['userId'], ['id'])
    op.drop_column('Prediction', 'user_id')
    op.add_column('Log', sa.Column('userId', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Log', type_='foreignkey')
    op.create_foreign_key('Log_userId_fkey', 'Log', 'User', ['userId'], ['id'])
    op.drop_column('Log', 'user_id')
    op.add_column('HospitalDomain', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('HospitalDomain', 'created_at')
    # ### end Alembic commands ###
