"""add confidence and image_url to Prediction

Revision ID: 6491a7b735da
Revises: 9e93f06151ab
Create Date: 2025-09-27 16:35:03.100073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6491a7b735da'
down_revision: Union[str, Sequence[str], None] = '9e93f06151ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prediction', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('Prediction', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Prediction', 'image_url')
    op.drop_column('Prediction', 'confidence')
    # ### end Alembic commands ###
