"""add recommendations column to Report

Revision ID: 885fb3d401b0
Revises: 33200f571060
Create Date: 2025-09-29 14:29:13.354252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885fb3d401b0'
down_revision: Union[str, Sequence[str], None] = '33200f571060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Report', 'recommendations')
    # ### end Alembic commands ###
