"""add name and npi_number to User

Revision ID: 9e93f06151ab
Revises: 8b2302a9ad56
Create Date: 2025-09-26 22:50:45.872326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e93f06151ab'
down_revision: Union[str, Sequence[str], None] = '8b2302a9ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(), nullable=True))
    op.add_column('User', sa.Column('npi_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'npi_number')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
