"""rename createdAt to created_at

Revision ID: c88efce9900f
Revises: 6491a7b735da
Create Date: 2025-09-29 13:46:51.687598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88efce9900f'
down_revision: Union[str, Sequence[str], None] = '6491a7b735da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Log', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('Log', 'createdAt')
    op.add_column('Prediction', sa.Column('userId', sa.UUID(), nullable=True))
    op.drop_constraint('Prediction_user_id_fkey', 'Prediction', type_='foreignkey')
    op.create_foreign_key(None, 'Prediction', 'User', ['userId'], ['id'])
    op.drop_column('Prediction', 'user_id')
    op.add_column('Report', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('Report', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('Report', 'created_at')
    op.add_column('Prediction', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Prediction', type_='foreignkey')
    op.create_foreign_key('Prediction_user_id_fkey', 'Prediction', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Prediction', 'userId')
    op.add_column('Log', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('Log', 'created_at')
    # ### end Alembic commands ###
